# Generated by Django 3.2.9 on 2021-11-17 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('other_field1', models.CharField(max_length=20)),
                ('other_field2', models.CharField(max_length=20)),
                ('other_field3', models.CharField(max_length=20)),
                ('other_field4', models.CharField(max_length=20)),
                ('other_field5', models.CharField(max_length=20)),
                ('other_field6', models.CharField(max_length=20)),
                ('other_field7', models.CharField(max_length=20)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
