# Generated by Django 3.2.9 on 2021-11-18 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='strict',
            new_name='strit',
        ),
    ]
